apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appcode
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AtitBimali/argo_infra.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: appcode

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true